#ifndef MAIN_H
#define MAIN_H

#define MAIN_GET_FILE_NAME				1
#define MAIN_FILE_READWRITE_OPEN		2
#define MAIN_FILE_CREATE				3
#define MAIN_FILE_READ					4
#define MAIN_INCREASE_INDEX				5
#define MAIN_FINISH_INIT_PROCESS		6

#define MAIN_CREAT_THREAD_CNT			32

#endif
