#ifndef POINT_OBSERVER_H
#define POINT_OBSERVER_H

#define POINT_OBSERVER_GET_FILE_NAME          		  1
#define POINT_OBSERVER_FILE_STATUS_CHECK	   		  2
#define POINT_OBSERVER_FILE_CREATE            		  3
#define POINT_OBSERVER_FILE_READ              		  4
#define POINT_OBSERVER_FILE_ACCESS_FAILED			  5
#define POINT_OBSERVER_INCREASE_INDEX    		      6
#define POINT_OBSERVER_FINISH_FILE_CHECK_PROCESS      7

#define POINT_OBSEVER_VALUE_CHANGE			1
#define POINT_OBSEVER_VALUE_NOT_CHANGE		0
#define POINT_OBSEVER_FILE_ERROR			-1


#endif
